name: C/C++ CI on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        chmod +x configure
        ./configure

    - name: Build
      run: make

    - name: Run Tests
      run: make check

    - name: Distribution Check
      run: make distcheck
