name: C/C++ Lint and Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build --config Debug
