name: CMake on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3' # Hoặc phiên bản Qt6 bạn đang dùng
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        OUTPUT_DIR="${{ github.workspace }}/build"
        echo "build-output-dir=$OUTPUT_DIR" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: >
        cmake --build ${{ steps.strings.outputs.build-output-dir }}
        --config Release

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release
